### ISSUE TITLE
Support node api documents?

### ISSUE THREAD

**Issue by southorange0929** [web-infra-dev/rspack-website#392] opened 2023-05-07 03:32 UTC
### What problem does this feature solve?

Just like webpack, it provide node api documents for us to custom pack logic.

### What does the proposed API of configuration look like?

https://webpack.js.org/api/node

**Comment by hardfist** [comment] 2023-08-17 07:12
duplicate of https://github.com/web-infra-dev/rspack-website/issues/403

**Closed by hardfist** 2023-08-17 07:13 UTC
Labels: documentation
